name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build-demo
      run: gcc -nostdlib -no-pie minil.S app.c -O2 -ffreestanding -o app
    - name: build-dem32
      run: gcc -nostdlib -no-pie -m32 minil.S app.c -O2 -ffreestanding -o app
